import type { Metadata } from 'next'
import { UserContextProvider } from '../context/UserContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body> <UserContextProvider>{children}</UserContextProvider></body>
    </html>
  )
}
